#!/bin/bash

# Ruta al directorio de tests
TEST_DIR="Selenium+Unit_test+Hooks.pruebas.test_flows"

# Ejecuta los tests con unittest
echo "Ejecutando tests en la carpeta '$TEST_DIR'..."
python -m unittest "$TEST_DIR"

# Verifica si los tests pasaron
if [ $? -ne 0 ]; then
    echo "❌ Tests fallaron. Cancela el push."
    exit 1
else
    echo "✅ Todos los tests pasaron. Procediendo con el push..."
fi
